version: "3.1"
services:
  odoo-17.0:
    user: root
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database-17.0:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=database-17.0
      - USER=odoo
      - PASSWORD=myodoo
      - ODOO_ENV=dev
    volumes:
      - "../custom_addons/:/opt/odoo/custom_addons/loistalagrand"
      - "../.git:/opt/odoo/.git"
      - "./.vscode:/opt/odoo/.vscode"
      - "./odoo.conf:/etc/odoo/odoo.conf"
    tty: true
  database-17.0:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5